site_name: CodeIgniter Shield OAuth
site_description: Documentation for Shield OAuth

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  font:
    text: Raleway
  palette:
    primary: red
    accent: red
  features:
    - navigation.sections
    - content.code.copy
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.action.edit
extra:
  homepage: https://codeigniter4.ir
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/datamweb/shield-oauth
      name: GitHub
  copyright: Copyright &copy; 2023 Pooya Parsa Dadashi

repo_url: https://github.com/datamweb/shield-oauth
edit_uri: edit/develop/docs/

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true

extra_css:
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.6.0/build/styles/github.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.6.0/build/highlight.min.js

nav:
  - Home: index.md
  - Links:
    - Installation Guide: install.md
    - How To Get Keys: get_keys.md
    - How to add other services: add_other_oauth.md
    - Quick Start: quickstart.md
